name: Build and Lint

on:
  push:
    branches: ["main"]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        # the Node.js versions to build on
        node-version: [14.x]

    steps:
      if: github.event_name == 'release' && startsWith(github.ref, 'refs/tags/v')
      
      - uses: actions/checkout@v2

      - name: Setup the node environment.
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}
          registry-url: "https://registry.npmjs.org/"
          
      - name: Install dependencies
        run: npm install

      - name: Lint the project
        run: npm run lint

      - name: Build the project
        run: npm run build
        env:
          CI: true

      - name: Install the package with a clean slate.
        run: npm ci

      - name: Publish the package to NPM.
        run: npm publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.npm_token }}
